### PR TITLE
PBI-21-newsletter details

### PR DESCRIPTION
**Pull request by reynaldi08**
In this branch, I create a page for see the details of each newsletter. There will be an images and the text based on the article that clicked to see more. Also there is a types for the newsletter that we clicked. 
Screenshot 2022-11-18 at 11 35 43

### CODE REVIEW

**Comment by reynaldi08** [comment]
Screenshot 2022-11-21 at 17 45 45
This is the performance of the newsletter details page. As you can see, there are no jank or shader in this page because the page just contain the text and the picture. For reloading the picture also just takes little time. However the average FPS is only 58 because from the previous page that I reload to get to the newsletter details page. The home for the newsletter also still very basic so there will be jank. But after merge, it might be there will be shader frame or if the news is connected to the API, it will takes time to loading the page for getting the images and all the text to load.

**Comment by anastasiaaaudiw** [comment]
Hi Aldi, after reviewing your pull request, here are some feedbacks:

### Commit messages and Pull request Requirements
- Please insert the test cases description into this UAT document which will be compiled with other test cases https://docs.google.com/spreadsheets/d/1fxoFl-MUUCEz4GXp8vNzCx2Z-too3pWjbYwPQh0sBig/edit#gid=1970821773
- After analyzing the codecov results, I see that you have successfully manage to achieve 100% code coverage 👍🏼
- You've implemented the `RED` and `GREEN` commit messages to give better clarity
- Your commit messages are very clear and simple which is really easy to understand

### Code Quality
- Overall I think you've manage to match your interface with the actual design. However I do think its better to reduce the size box in between the back arrow and article tag.
- Another thing is to give navbar at every article detail page so users can easily navigate to other pages.

Aside from that, I think you're good to merge this branch to staging, so we can continue connecting with the Heroku database.

**Comment by annesafrina** [comment]
Hi, Aldi! I think your interface is already good. However, if we refer to the design, the gap between the arrow icon and "tips for you" icon is quiet large compared to the design in our Figma. I would like to suggest, maybe instead of putting the _EdgeInsets.all(l20)_ 
you can add 
_EdgeInsets.only(left: 20.0, right: 20.0)_
and add
_SizedBox(
                height: 12,
              ),_
so that it will create the suitable space between the two, while maintaining the left and right padding. 
Thank you.

**Comment by reynaldi08** [comment]
Hello everyone,

I would like to add about the [UAT](https://docs.google.com/spreadsheets/d/1fxoFl-MUUCEz4GXp8vNzCx2Z-too3pWjbYwPQh0sBig/edit#gid=1111312888) of this sprint that related to this branch. Thank you!

**Pull request merged**
