### PR TITLE
PBI-18-Refactor report interface

### PR DESCRIPTION
**Pull request by reynaldi08**
In this branch, I fix the design for the report page which include the pie chart and the tap button. So basically, the pie chart now can show the how many transaction in a month.

### CODE REVIEW

**Comment by reynaldi08** [comment]
In this branch I change the ways of user see they reports. In this branch the report will select the month they want to see and submit the month. Then, the report page will show the report based on the month that already chosen. 
This is the input page for the report:

Screenshot 2022-12-07 at 18 06 43


And this is the report page after I fix it in this branch:
Screenshot 2022-12-07 at 18 20 16

**Comment by reynaldi08** [comment]
For profiling in these two pages, the first page for input number have the average of 57 FPS. There are some jank when the user click the to choose the month and when the user choose the month. I think is because of the circle that cover the month when we choose the month.

Screenshot 2022-12-07 at 18 45 37


Also in the report page, there are 1 big jank means it takes time to shows the render of the UI. It's because of the circular/ pie chart that need times to calculate from the data given. Also the report page is still continue to take the data every second so it still continue to loading until the user move from the report page. The average FPS of the report page is 56 FPS because of the one big jank frame. However, after finish render the pie chart, the performance in that page come back to stable.
Screenshot 2022-12-07 at 18 46 48

**Comment by annesafrina** [comment]
Hi Reynaldi, upon looking at your pull request, i'd like to give you some feedbacks.

Commit messages and Pull request Requirements
Please insert the test cases description into this UAT document below:
https://docs.google.com/spreadsheets/d/1fxoFl-MUUCEz4GXp8vNzCx2Z-too3pWjbYwPQh0sBig/edit#gid=1970821773
After looking at the codecov report, I think you need to improve the coverage for the report page.
You've implemented the RED, GREEN, REFACTOR label on your commit message, which I think serves as a clear description of your work.
Code Quality
As for the interface appearance, I think you have done a very great job on fixing the display of the pie chart as well as other aspects of the interface. 
That is all from me.
Thank you, Aldi!

**Comment by anastasiaaaudiw** [comment]
Hi Aldi, I think overall your progress is already good as you've attempted to match the interface with the figma design. However one thing I'd like to point out maybe fix the padding or margin between the container/items so it can look consistent and cohesive with other pages. Aside from that, I think it looks great!

**Pull request merged**
